import streamlit as st
from pathlib import Path

# Page config
st.set_page_config(page_title="Amherst Skills Module")

# Track current page
if "page" not in st.session_state:
    st.session_state.page = "intro"


def go_to_page(page_name: str):
    st.session_state.page = page_name


# ------------------- PAGE 1 -------------------
if st.session_state.page == "intro":

    st.title("Introduction to Liberal Arts Career Exploration")

    st.markdown(
        """
        Welcome! In the next two modules we are going to explore how your Amherst curriculum supported the 
        development of skills that will help you become employed. 

        The first module will guide you through an exploration of your Amherst courses and the skills you 
        developed by taking them. The second module will guide you through searching for jobs of interest 
        to you and setting you up for the synchronous mock interview.

        In the first module, you will:

        1. Create your own representation of your Amherst curriculum  
        2. Identify where in your curriculum you developed important skills  
        3. Identify anecdotes from your Amherst courses that showcase your development and use of these skills
        4. Share your work with your peers  
        5. Explore the similarities and differences between your curricular representation  
           and the curricular representation generated by the Visual Open Curriculum tool  

        """
    )

    # Continue button
    if st.button("Begin Module One"):
        go_to_page("page_2")


# ------------------- PAGE 2 -------------------
elif st.session_state.page == "page_2":

    st.title("Module One: Part One")

    st.markdown(
        """
        To begin, please watch the video below to learn more about this workshop series and the benefit of 
        liberal arts skills in the 21st-century workplace:
        """
    )

    # Intro video
    video_path = Path(__file__).parent / "with_subtitles (1).mp4"
    if video_path.exists():
        st.video(str(video_path))
    else:
        st.error(f"Video file not found at: {video_path}")

    st.markdown(
        """
        If you are interested in viewing the percentages of cross-disciplinary employers that find particular skills 
        important, please view the following chart from Rios et al (2020). The chart was created from a descriptive analysis of 
        142,000 job advertisements across disciplines
        """
    )

    st.image(
        "Rios_et_al_chart.png",
        caption="Figure from Rios et al (2020) showing the percentage of cross-disciplinary employers that find particular skills important."
    )

    # Continue button
    st.markdown("---")
    if st.button("Continue"):
        go_to_page("page_3")


# ------------------- PAGE 3 -------------------
elif st.session_state.page == "page_3":

    st.title("Module One: Part Two")

    st.markdown(
        """
        Thank you for watching the introduction video. Now, you are going to have the opportunity 
        to create a visual representation of how you think the courses you have taken at Amherst 
        College relate to one another.

        To complete this activity, you have options:

        Option 1:
        You can create your map using physical paper or markers, or you can also create it online using 
        software like Google Drawings. The example student map below measures similarity with the
        student’s level of comfort on the Y-Axis. In contrast, the X-Axis organizes this 
        students’ learning with. You can map how similar you think the courses were to each 
        other using different dimensions that you choose like the example, or you can exclude particular
        dimensions. It is all up to you!”
        """
    )

    st.image("IMG_0061.PNG", caption="Example student course map.")

    st.markdown(
        """
        Option 2: 
        If you do not want to or are unable to create a visual representation of your courses, 
        you can relate their similarity in prose or in chart form.
        """
    )

    st.image("IMG_0064.PNG", caption="Example student course similarity chart.")

    st.markdown(
        """
        Option 3:
        If there is any other way that you would like to describe the similarity between the 
        courses you took, please feel free to create or write this type of representation.
        """
    )

    # Continue button
    st.markdown("---")
    if st.button("Continue"):
        go_to_page("page_4")


# ------------------- PAGE 4 -------------------
elif st.session_state.page == "page_4":

    st.title("Module One: Part Three")

    st.markdown(
        """
        Great job! Now, let’s revise our representations to find trends in the skills you learned 
        in different courses and how those skills relate to each other
        """
    )

    st.markdown(
        """
        If you completed Option A: you can use a new color to draw lines between courses where you 
        developed particular skills. At the bottom of the page is the skill chart from Rios et al (2020), 
        listing the percentages of job advertisements that mention a particular skill. You can choose to 
        use skill(s) mentioned in this chart or choose to feature a different set of skills that is 
        pertinent to your particular career pathway. In the example below, the student chose some skills
        from Rios et al (2020) as well as skills like “curriculum design,” which are important for her 
        career path in education. In the example below, the student used one color per skill and marked 
        the courses where they learned this skill with this color. Then, they drew lines between
        the courses where they learned this skill with the same colors.
        """
    )

    st.image("IMG_0062.PNG", caption="Example revised student course map.")

    st.markdown(
        """
        If you completed Option 2: you can also use different colors to note the courses where you 
        developed certain skills. Additionally, you can use different fonts or completely write the 
        skills and similarities out in prose!” 
        """
    )

    st.image("IMG_0066.PNG", caption="Example course similarity chart with annotated skills.")

    st.markdown(
        """
        For any option: you can do whatever you feel like provides the best representation of 
        skillset within your curricular representation.
        """
    )

    # Continue button
    st.markdown("---")
    if st.button("Continue"):
        go_to_page("page_5")


# ------------------- PAGE 5 -------------------
elif st.session_state.page == "page_5":

    st.title("Module One: Part Four")

    st.markdown(
        """
        Wonderful job! Now, we are going to share our representations on Padlet. The link to the Padlet 
        is below this text. In addition to the representation itself, you should also share 
        five specific instances in your coursework where you developed/ displayed each of the skills you
        chose. For instance, our example student offered the following five instances of skill development 
        from their time at Amherst that correlate with the five skills they chose to track. Please also view 
        the posts of other students. You can comment on other people's posts if you find their visualization 
        interesting or have questions. Return to this page when you are done to move onto the last part of module one.
        """
    )

    st.markdown(
        """
        **Padlet link for Module 1:**  
        https://padlet.com/ravitcham/making-our-own-visual-open-curriculum-xqv4hg4caejkhvdm
        """
    )

    st.markdown("---")
    if st.button("Continue"):
        go_to_page("page_6")


# ------------------- PAGE 6 -------------------
elif st.session_state.page == "page_6":

    st.title("Module One: Part 5")

    st.markdown(
        """
        Now, you are going to (if you have not already) enter the courses you took at Amherst College 
        in the Visual Open Curriculum app. While you are viewing the visualization generated by the app,
        you will take a screenshot of it to post as a comment under your original post on Padlet. We will
        revisit the similarities and differences between your hand-made representations of your 
        curriculum and the representations generated by the Visual Open Curriculum, during our 
        in-person session, but for now, please add a comment to your post if viewing the version of 
        your curriculum created by the WebApp made you think differently about the skill relationships 
        you identified between courses or the way you created your representation. You can also note in
        these comments ways in which you disagree with the representation created by 
        the Visual Open Curriculum. Please also view your peer's comments on their Visual Open Curriculum 
        comparisons, responding when you see commentary that resonates with you or that you disagree with.
        When you are finished adding to the Padlet, please return to this
        WebPage and click continue to continue to move on to Module 2 
        """
    )

    st.markdown(
        """
        **Padlet link for Module 1:**  
        https://padlet.com/ravitcham/making-our-own-visual-open-curriculum-xqv4hg4caejkhvdm
        """
    )

    st.markdown("---")
    if st.button("Continue"):
        go_to_page("page_7")


# ------------------- PAGE 7 -------------------
elif st.session_state.page == "page_7":

    st.title("Module Two: Part One")

    video_path = Path(__file__).parent / "resized.mp4"
    if video_path.exists():
        st.video(str(video_path))
    else:
        st.error(f"Video file not found at: {video_path}")

    st.markdown("---")
    if st.button("Continue"):
        go_to_page("page_8")


# ------------------- PAGE 8 -------------------
elif st.session_state.page == "page_8":

    st.title("Module Two: Part Two")

    st.markdown(
        """
        Welcome to the first part of the second Module! Now that we have identified our 
        marketable skills and anecdotes, we are going to find actual jobs to apply to.

        Using a job search website, like Handshake or Indeed, find 5 jobs you are 
        interested in applying to. Keep a list of these jobs on a piece of paper or in an online 
        document.

        When you are finished searching for these jobs, click the **Continue** button.
        """
    )

    st.markdown("### Suggested Job Boards")
    st.markdown(
        """
        Handshake: https://amherst.joinhandshake.com/login  
        Indeed: https://www.indeed.com  
        Idealist (Nonprofits): https://www.idealist.org  
        Glassdoor: https://www.glassdoor.com  
        """
    )

    st.markdown("---")
    if st.button("Continue to Next Step"):
        go_to_page("page_9")


# ------------------- PAGE 9 -------------------
elif st.session_state.page == "page_9":

    st.title("Module Two: Part Three ")

    st.markdown(
        """
        Great job finding five jobs of interest to you! Now, you are going to choose one of
        these jobs that you would like to practice interviewing for, and you are going to post which
        job you chose, and the reason you chose it, on the job-Board Padlet for Module 2. Please be
        sure to include the actual link to the job that you chose in your Padlet post. Please also 
        note in your padlet post which skills, which you identified in the first module, you believe,
        based on the job posting, would be the most useful to highlight during the interview for 
        the job you chose. Please mention any specific anecdotes you brainstormed in Module 1 that
        would be particularly useful for this job interview! Please view your peers posts and 
        comment on their posts when the jobs they are exploring are of interest to you, or when you
        have questions for them. When you are done, come back to this page and click the continue button
        """
    )

    st.markdown("### Module 2 Job Board Padlet")
    st.markdown("https://padlet.com/ravitcham/career-exploration-75ljgzl81pbbn7s4")

    st.markdown("---")
    if st.button("Continue"):
        go_to_page("page_10")


# ------------------- PAGE 10 -------------------
elif st.session_state.page == "page_10":

    st.title("Congratulations On Finishing The Asynchronous Activities!")

    st.markdown(
        """
        Great job! Thank you so much for all of your hard work in completing these 2 Modules! When we
        meet in person, you will complete a mock interview with a peer who has a similar industry
        interest to you. To prepare, please respond to your post on the Module 2 Padlet with a pdf
        file of your resume. We will print your resume, job description, and list of Amherst skills
        and anecdotes for your peer interviewer. If you would like to, you can edit your resume to 
        highlight the skills and anecdotes you identified as in Module 1. This editing however, is 
        optional!
        """
    )

    st.markdown("---")



